Fix delivery script

diff --git a/scripts/deliver b/scripts/deliver
--- a/scripts/deliver
+++ b/scripts/deliver
@@ -13,8 +13,15 @@ function main
   echo "Delivering [$NAME]"
   make clean
   ./check
-  deliverBinaryVersion
-  #deliverWebVersion
+
+  echo "-------------------------------------"
+  echo "Building resources"
+  rm -rf res
+  make -j`nproc` resources >/dev/null
+
+  (deliverBinaryVersion)
+  (deliverWebVersion)
+  echo OK
 }
 
 function deliverBinaryVersion
@@ -31,7 +38,7 @@ function deliverBinaryVersion
 
   # Windows binaries
   BIN_WIN=$tmpDir/bin/w64
-  CXXFLAGS="" \
+  CXXFLAGS="-O3" \
   BIN=$BIN_WIN \
     ./scripts/w64-make -j`nproc` \
     VERSION="$version" \
@@ -44,10 +51,13 @@ function deliverBinaryVersion
   cp /usr/x86_64-w64-mingw32/lib/libwinpthread-1.dll                 $tmpDir/$N
   cp /usr/lib/gcc/x86_64-w64-mingw32/$gccVersion/libstdc++-6.dll     $tmpDir/$N
   cp /usr/lib/gcc/x86_64-w64-mingw32/$gccVersion/libgcc_s_seh-1.dll  $tmpDir/$N
-  cp /opt/envs/win64/bin/SDL2.dll                                    $tmpDir/$N
+  cp /opt/envs/x86_64-w64-mingw32/bin/SDL2.dll                       $tmpDir/$N
 
   # GNU/Linux binaries
-  CXXFLAGS="-include extra/glibc_version.h" \
+  export PATH="/opt/toolchains/x86_64-ace-linux-gnu/bin:$PATH"
+  CROSS_COMPILE=x86_64-ace-linux-gnu- \
+  PKG_CONFIG_LIBDIR="/opt/envs/x86_64-ace-linux-gnu/lib/pkgconfig" \
+  CXXFLAGS="-O3" \
   BIN=$tmpDir/bin/gnu \
     make -j`nproc` \
     VERSION="$version" \
@@ -81,35 +91,41 @@ function deliverBinaryVersion
 function deliverWebVersion
 {
   echo "-------------------------------------"
-  echo "Building Web version"
-  BIN=bin/asmjs \
-    scripts/asmjs-make -j`nproc` bin/asmjs/rel/game.html
+  echo "Building web version"
 
-  #------------------------------------------------------------------------------
-  # create game directory
-  #------------------------------------------------------------------------------
-  readonly gameDir=$tmpDir/$NAME
-  mkdir -p $gameDir
+  if ! which emcc >/dev/null ; then
+    echo "emcc was not found in PATH" >&2
+    echo "Did you forget to: source ~/source/emsdk/emsdk_env.sh" ? >&2
+    return 1
+  fi
 
-  cp -a bin/asmjs/rel/* $gameDir
-  cp index.html $gameDir/index.html
+  mkdir $tmpDir/pkgconfig
 
-  #------------------------------------------------------------------------------
-  # archive it
-  #------------------------------------------------------------------------------
-  pushd $tmpDir
-  zip $NAME.zip -r $NAME
-  popd
+  genPkgConfigSdl2 > $tmpDir/pkgconfig/sdl2.pc
 
-  mv $tmpDir/$NAME.zip .
+  export BIN=$tmpDir/bin/web
+  export PKG_CONFIG_LIBDIR=$tmpDir/pkgconfig
+  export CXX=emcc
+  export EXT=".html"
+  export DBGFLAGS=""
+  export CXXFLAGS="-O3 -g0 -DNDEBUG"
+  export LDFLAGS="-O3 -g0 --use-preload-plugins --pre-js \"my-pre.js\" --preload-file res -s USE_WEBGL2=1 -s TOTAL_MEMORY=$((64 * 1024 * 1024)) -s PRECISE_F32=1"
 
-  #------------------------------------------------------------------------------
-  # upload it to code.alaiwan.org
-  #------------------------------------------------------------------------------
-  rsync \
-    --compress \
-    --delete \
-    -vr $gameDir/* alaiwans@code.alaiwan.org:public_html/games/$NAME
+  make -j`nproc` game >/dev/null
+
+  rm -f /tmp/$NAME-web.zip
+  (cd $tmpDir/bin/web/rel && zip /tmp/$NAME-web.zip -r . )
+
+  du -hs /tmp/$NAME-web.zip
+}
+
+function genPkgConfigSdl2
+{
+  echo "Name: sdl2"
+  echo "Version: 2.0.0"
+  echo "Description: placeholder pc file"
+  echo "Libs: -s USE_SDL=2"
+  echo "Cflags:  -s USE_SDL=2"
 }
 
 main
